/**/*:
  ros__parameters:
    broker:
      host: fms.bzlrobot.com
      port: 2884
      tls:
        enabled: true
        # ca_certificate: /home/nick/zhengping_ws/mqtt_client_ws/install/mqtt_client/share/mqtt_client/config/rootCA.ros2.pem
    client:
      # id: "ZHENGPING-001"
      clean_session: false
      keep_alive_interval: 60.0
      tls:
        verify: false
        version: 3 # TLS v1.2
    bridge:
      ros2mqtt:
        ros_topics:
          - /ping/primitive
          - /device/exception
          - /device/all_exception
          - /device/deviceinfo
        /ping/primitive:
          mqtt_topic: pingpong/primitive
          primitive: true
        /device/exception:
          # mqtt_topic: /device/ZHENGPING-001/exception
          primitive: true
          ros_type: std_msgs/msg/String
          advanced:
            mqtt:
              qos: 1
              retained: false
        /device/all_exception:
          # mqtt_topic: /device/ZHENGPING-001/all-exception
          primitive: true
          ros_type: std_msgs/msg/String
          advanced:
            mqtt:
              qos: 1
              retained: false
        /device/deviceinfo:
          # mqtt_topic: /device/ZHENGPING-001/deviceinfo
          primitive: true
          ros_type: std_msgs/msg/String
          advanced:
            mqtt:
              qos: 1
              retained: false
      mqtt2ros:
        mqtt_topics:
          - pingpong/primitive
        pingpong/primitive:
          ros_topic: /pong/primitive
          primitive: true
